### ISSUE TITLE
OSError: decompression fails

### ISSUE THREAD

**Issue by InventoRyAlpaca** [jspaezp/timsrust_pyo3#8]
Hello, 

I installed via pip and threw together the following script (partially borrowed from the bruker timsdata_example.py file) 

```import timsrust_pyo3
import sys
import  os

if len(sys.argv) < 2:
    raise RuntimeError("need arguments: tdf_directory")
path = sys.argv[1]
parent_dir = []

for root, dirs, files in os.walk(path):
    for dirname in dirs:
        #print(dirname)
        if dirname.endswith('.d'):
            print(os.path.join(root,dirname))
            parent_dir.append(os.path.join(root,dirname))

def partial_dump():
    for analysis_dir in parent_dir:
        print(analysis_dir)
        specs = timsrust_pyo3.read_all_spectra(analysis_dir)
        print(specs[0])

if __name__ == "__main__":
    partial_dump()```

Which produces the following terminal output.

```
PS C:\Users\ira.gray\Downloads\timsdata-2.21.0.4\timsdata\examples\py> py .\timsrust_pyo3_test.py "C:\Users\ira.gray\Documents\My Projects\2024_10\20241016_15Min"
C:\Users\ira.gray\Documents\My Projects\2024_10\20241016_15Min\20241016_HekWholeDDA_5kCell_1_BA4_1_7879.d
C:\Users\ira.gray\Documents\My Projects\2024_10\20241016_15Min\20241016_HekWholeDDA_5kCell_2_BA5_1_7880.d
C:\Users\ira.gray\Documents\My Projects\2024_10\20241016_15Min\20241016_HekWholeDDA_5kCell_3_BA6_1_7881.d
C:\Users\ira.gray\Documents\My Projects\2024_10\20241016_15Min\20241016_MthBlkDDA_5kCell_1_BB4_1_7878.d
C:\Users\ira.gray\Documents\My Projects\2024_10\20241016_15Min\20241016_MthBlkDDA_5kCell_2_BB5_1_7882.d
C:\Users\ira.gray\Documents\My Projects\2024_10\20241016_15Min\20241016_HekWholeDDA_5kCell_1_BA4_1_7879.d
Traceback (most recent call last):
  File "C:\Users\ira.gray\Downloads\timsdata-2.21.0.4\timsdata\examples\py\timsrust_pyo3_test.py", line 24, in <module>
    partial_dump()
  File "C:\Users\ira.gray\Downloads\timsdata-2.21.0.4\timsdata\examples\py\timsrust_pyo3_test.py", line 20, in partial_dump
    specs = timsrust_pyo3.read_all_spectra(analysis_dir)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: Decompression fails
```

Any ideas?

**Comment by jspaezp** [comment]
Hey there! I am sincerely sorry I missed this notification! (in the future feel free to ping back if I have not replied in more than a week, I am also in bluesky if you want to publicly shame me :P) Do you still have the problem with the current version?

**Comment by jspaezp** [comment]
BTW: what I am getting here is that one of the files seems to be broken. It is semi-normal for a couple of scans to be corrupt (I have seen it relatively often in Pro2 data, never in scp, ultra). And unfortunately right now it reads everything in an all-or-nothing way, so a single broken scan will error out in the reader (with that not-very-informative error message).

I will see if I can add an optional argument that warns/skips of errors instead of failing totally.

**Comment by jspaezp** [comment]
Hi!

Me again ... I added lazy iteration, so now you can actualy figure out what scan is going wrong. (I have not yet added the "skip bad scan options though")

To see if you file is completely ruined or if it is only a couple of bad spectra I would run something like so ...

```
import sys
from pathlib import Path

if len(sys.argv) < 2:
    raise RuntimeError("need arguments: tdf_directory")
path = sys.argv[1]
parent_dir = list(Path(path).rglob("*.d"))
print(parent_dir)

def partial_dump():
    for analysis_dir in parent_dir:
        print(analysis_dir)
        specs = timsrust_pyo3.SpectrumReader(analysis_dir) # Note the change here
        last_good = 0
        try:
            for i, s in range(len(specs)):
                _ = specs.get(i)
                last_good = i
            print("ALL GOOD HERE!!!")
        except OsError:
            print("Found an error in spectrum")
            print(f"last good -> {last_good}")

```
